### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by xp-bear** [DWHengr/flash#1]

**Comment by xp-bear** [comment]
要学习rust之后，在学习tauri

**Comment by DWHengr** [comment]
如果你所做的应用，只关注UI层（和web开发一样），对系统层操作的比较少，rust可以先了解，不用太深入。只需要会使用tauri的一些特性，如系统托盘、菜单、事件等，即可开发一个桌面程序。前提你需要具有前端开发的技能。
